---
version: '3.8'
name: "mc-imageopt"

x-db-user: &db-user
  "moodle"
x-db-pass: &db-pass
  "m@0dl3ing"
x-db-name: &db-name
  "imageopt-moodle"
x-db-container-name: &db-container-name
  "imageopt-db"
x-moodle-container-name: &moodle-container-name
  "imageopt-moodle"

services:
  moodle:
    container_name: *moodle-container-name
    build:
      context: .
      dockerfile: C:\Moodle\mchef\.mchef/docker/Dockerfile
    environment:
      DB_USER: *db-user
      DB_PASS: *db-pass
      DB_NAME: *db-name
      DB_TYPE: pgsql
      DB_HOST: *db-container-name
    ports:
      - 80:80
    extra_hosts:
      - "moodle-image-opt.test:127.0.0.1"
    volumes:
      - "moodledata:/var/www/moodledata"
  db:
    container_name: *db-container-name
    image: postgres:13
    environment:
      POSTGRES_USER: *db-user
      POSTGRES_PASSWORD: *db-pass
      POSTGRES_DB: *db-name


volumes:
  moodledata:
